# Generated by Django 5.2.9 on 2025-12-26 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Наименование")),
                ("deadline", models.DateTimeField(verbose_name="Срок")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("inactive", "Не активна"), ("active", "В работе"), ("complete", "Выполнена")],
                        default="inactive",
                        max_length=20,
                        null=True,
                        verbose_name="Статус выполнения",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.tasks",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
