# Generated by Django 5.2.9 on 2025-12-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                ("middle_name", models.CharField(blank=True, max_length=150, null=True, verbose_name="Отчество")),
                ("position", models.CharField(max_length=200, verbose_name="Должность")),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
